#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before pushing'

# # Check Ts
npm run type-check ||
(
    echo '🚨🚨🚨🚨🚨🚨 - Your ts has some error. 🤢🤮🤢🤮
        Check Failed. Run npm run format, add changes and try commit and push again.';
    false;
)

# # Check Prettier standards
npm run check:format ||
(
    echo '🎨🎨🎨🎨🎨🎨 - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit and push again.';
    false;
)

# # Check lint
npm run lint ||
(
    echo '👕👕👕👕👕👕👕 - Your lint looks disgusting. 🤢🤮🤢🤮
            Linter Check Failed. Fix all errors and warnings bellow, add changes and try commit and push again.';
    false;
)

# If everything passes... Now we can push
echo '✅✅✅✅ You win this time... I am pushing this now. ✅✅✅✅'

